generator:
  class: tmcTwitterBootstrapDoctrineGenerator
  param:
    model_class:           VtCttTransaction
    theme:                 tmcTwitterBootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          vt_ctt_transaction_vtRegistrationFixedReport
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Registration Fixed Report
        display: [order_no,isdn,service_type,ctt_package_name,prepaid_code,total_fee,policy,created_at,tran_id,ctt_id,status_name,omni_error_code_name]
        fields:
          isdn: {label: SĐT đăng ký/acc đăng ký dịch vụ}
          service_type: {label: Loại dịch vụ}
          ctt_package_name: {label: Gói cước}
          prepaid_code: {label: Mã cước đóng trước}
          total_fee: {label: Tổng tiền}
          policy: {label: Chính sách đóng cước trước}
          created_at: {label: Thời gian đăng ký}
          tran_id: {label: Mã thanh toán (Mã sinh ra từ MyVT)}
          ctt_id: {label: Mã giao dịch (Mã sinh ra từ Cổng thanh toán)}
          status_name: {label: Trạng thái trừ tiền}
          omni_error_code_name: {label: Trạng thái đơn hàng}
        object_actions: {}
        batch_actions: {}
        actions: {}
      filter:
        class: vtRegistrationFixedReportAdminFormFilter
      form:    ~
      edit:    ~
      new:     ~
      show:    ~
      revert:  ~