<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('VtVpgTransaction', 'doctrine');

/**
 * BaseVtVpgTransaction
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $calling
 * @property integer $isdn
 * @property string $tran_id
 * @property integer $amount
 * @property string $ctt_id
 * @property integer $status
 * @property string $error_code
 * @property string $error_message
 * @property integer $is_refund
 * @property integer $retry
 * @property string $channel
 * @property string $isdn_login
 * @property datetime $order_time
 * @property string $service_indicator
 * @property Doctrine_Collection $VtCttTransaction
 * 
 * @method string              getCalling()           Returns the current record's "calling" value
 * @method integer             getIsdn()              Returns the current record's "isdn" value
 * @method string              getTranId()            Returns the current record's "tran_id" value
 * @method integer             getAmount()            Returns the current record's "amount" value
 * @method string              getCttId()             Returns the current record's "ctt_id" value
 * @method integer             getStatus()            Returns the current record's "status" value
 * @method string              getErrorCode()         Returns the current record's "error_code" value
 * @method string              getErrorMessage()      Returns the current record's "error_message" value
 * @method integer             getIsRefund()          Returns the current record's "is_refund" value
 * @method integer             getRetry()             Returns the current record's "retry" value
 * @method string              getChannel()           Returns the current record's "channel" value
 * @method string              getIsdnLogin()         Returns the current record's "isdn_login" value
 * @method datetime            getOrderTime()         Returns the current record's "order_time" value
 * @method string              getServiceIndicator()  Returns the current record's "service_indicator" value
 * @method Doctrine_Collection getVtCttTransaction()  Returns the current record's "VtCttTransaction" collection
 * @method VtVpgTransaction    setCalling()           Sets the current record's "calling" value
 * @method VtVpgTransaction    setIsdn()              Sets the current record's "isdn" value
 * @method VtVpgTransaction    setTranId()            Sets the current record's "tran_id" value
 * @method VtVpgTransaction    setAmount()            Sets the current record's "amount" value
 * @method VtVpgTransaction    setCttId()             Sets the current record's "ctt_id" value
 * @method VtVpgTransaction    setStatus()            Sets the current record's "status" value
 * @method VtVpgTransaction    setErrorCode()         Sets the current record's "error_code" value
 * @method VtVpgTransaction    setErrorMessage()      Sets the current record's "error_message" value
 * @method VtVpgTransaction    setIsRefund()          Sets the current record's "is_refund" value
 * @method VtVpgTransaction    setRetry()             Sets the current record's "retry" value
 * @method VtVpgTransaction    setChannel()           Sets the current record's "channel" value
 * @method VtVpgTransaction    setIsdnLogin()         Sets the current record's "isdn_login" value
 * @method VtVpgTransaction    setOrderTime()         Sets the current record's "order_time" value
 * @method VtVpgTransaction    setServiceIndicator()  Sets the current record's "service_indicator" value
 * @method VtVpgTransaction    setVtCttTransaction()  Sets the current record's "VtCttTransaction" collection
 * 
 * @package    cms_ctt
 * @subpackage model
 * @author     viettel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVtVpgTransaction extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vt_vpg_transaction');
        $this->hasColumn('calling', 'string', 50, array(
             'type' => 'string',
             'comment' => 'So dien thoai thanh toan',
             'length' => 50,
             ));
        $this->hasColumn('isdn', 'integer', 20, array(
             'type' => 'integer',
             'comment' => 'so dien thoai thu huong',
             'length' => 20,
             ));
        $this->hasColumn('tran_id', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Ma giao dich ben myviettel tu sinh',
             'length' => 255,
             ));
        $this->hasColumn('amount', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'So tien can thanh toan',
             'length' => 11,
             ));
        $this->hasColumn('ctt_id', 'string', 255, array(
             'type' => 'string',
             'comment' => 'id giao dịch bên ctt, trả về trong payRessult',
             'length' => 255,
             ));
        $this->hasColumn('status', 'integer', 2, array(
             'type' => 'integer',
             'comment' => '0: gạch nợ thất bại, 1: gạch nợ thành công',
             'length' => 2,
             ));
        $this->hasColumn('error_code', 'string', 45, array(
             'type' => 'string',
             'comment' => '00: là thành công,33: timeOut,23: số điện thoại lỗi, Còn lại là lỗi không thể thanh toán trên VPG ',
             'length' => 45,
             ));
        $this->hasColumn('error_message', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Mo ta loi',
             'length' => 255,
             ));
        $this->hasColumn('is_refund', 'integer', 2, array(
             'type' => 'integer',
             'default' => 0,
             'comment' => '0 chưa hoàn tiền, 1 đã hoàn tiền (mặc định = 0)',
             'length' => 2,
             ));
        $this->hasColumn('retry', 'integer', 2, array(
             'type' => 'integer',
             'default' => 0,
             'comment' => 'Số lần retry giao dịch',
             'length' => 2,
             ));
        $this->hasColumn('channel', 'string', 255, array(
             'type' => 'string',
             'default' => 0,
             'comment' => 'Kênh dich vụ tích hợp vào thanh toán APP,WEB,WAP',
             'length' => 255,
             ));
        $this->hasColumn('isdn_login', 'string', 15, array(
             'type' => 'string',
             'comment' => 'SDT dang nhap myviettel',
             'length' => 15,
             ));
        $this->hasColumn('order_time', 'datetime', null, array(
             'type' => 'datetime',
             'comment' => 'thoi gian dat hang tren myviettel',
             ));
        $this->hasColumn('service_indicator', 'string', 10, array(
             'type' => 'string',
             'comment' => 'dung de truyen sang ws gach no',
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('VtCttTransaction', array(
             'local' => 'tran_id',
             'foreign' => 'tran_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}