<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('VtArea', 'doctrine');

/**
 * BaseVtArea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $code
 * @property string $parent_code
 * @property string $name
 * @property string $full_name
 * @property integer $status
 * @property string $province
 * @property string $district
 * @property string $precinct
 * @property string $street_block
 * @property string $street
 * @property integer $province_name
 * @property integer $district_name
 * @property string $precinct_name
 * 
 * @method string  getCode()          Returns the current record's "code" value
 * @method string  getParentCode()    Returns the current record's "parent_code" value
 * @method string  getName()          Returns the current record's "name" value
 * @method string  getFullName()      Returns the current record's "full_name" value
 * @method integer getStatus()        Returns the current record's "status" value
 * @method string  getProvince()      Returns the current record's "province" value
 * @method string  getDistrict()      Returns the current record's "district" value
 * @method string  getPrecinct()      Returns the current record's "precinct" value
 * @method string  getStreetBlock()   Returns the current record's "street_block" value
 * @method string  getStreet()        Returns the current record's "street" value
 * @method integer getProvinceName()  Returns the current record's "province_name" value
 * @method integer getDistrictName()  Returns the current record's "district_name" value
 * @method string  getPrecinctName()  Returns the current record's "precinct_name" value
 * @method VtArea  setCode()          Sets the current record's "code" value
 * @method VtArea  setParentCode()    Sets the current record's "parent_code" value
 * @method VtArea  setName()          Sets the current record's "name" value
 * @method VtArea  setFullName()      Sets the current record's "full_name" value
 * @method VtArea  setStatus()        Sets the current record's "status" value
 * @method VtArea  setProvince()      Sets the current record's "province" value
 * @method VtArea  setDistrict()      Sets the current record's "district" value
 * @method VtArea  setPrecinct()      Sets the current record's "precinct" value
 * @method VtArea  setStreetBlock()   Sets the current record's "street_block" value
 * @method VtArea  setStreet()        Sets the current record's "street" value
 * @method VtArea  setProvinceName()  Sets the current record's "province_name" value
 * @method VtArea  setDistrictName()  Sets the current record's "district_name" value
 * @method VtArea  setPrecinctName()  Sets the current record's "precinct_name" value
 * 
 * @package    cms_ctt
 * @subpackage model
 * @author     viettel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVtArea extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vt_area');
        $this->hasColumn('code', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Ma code',
             'length' => 255,
             ));
        $this->hasColumn('parent_code', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Ma code cua thang cha',
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Ten',
             'length' => 255,
             ));
        $this->hasColumn('full_name', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Ten day du',
             'length' => 255,
             ));
        $this->hasColumn('status', 'integer', 2, array(
             'type' => 'integer',
             'comment' => 'Trang thai',
             'length' => 2,
             ));
        $this->hasColumn('province', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Tinh thanh',
             'length' => 255,
             ));
        $this->hasColumn('district', 'string', 50, array(
             'type' => 'string',
             'comment' => 'Quan huyen',
             'length' => 50,
             ));
        $this->hasColumn('precinct', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Phuong xa',
             'length' => 255,
             ));
        $this->hasColumn('street_block', 'string', 50, array(
             'type' => 'string',
             'comment' => 'To thon',
             'length' => 50,
             ));
        $this->hasColumn('street', 'string', 50, array(
             'type' => 'string',
             'comment' => 'Duong',
             'length' => 50,
             ));
        $this->hasColumn('province_name', 'integer', 20, array(
             'type' => 'integer',
             'comment' => 'Ten tinh thanh',
             'length' => 20,
             ));
        $this->hasColumn('district_name', 'integer', 20, array(
             'type' => 'integer',
             'comment' => 'Ten qan huyen',
             'length' => 20,
             ));
        $this->hasColumn('precinct_name', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Ten to thon',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}