<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PartnerTransaction', 'doctrine');

/**
 * BasePartnerTransaction
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $transaction_id
 * @property string $description
 * @property string $myviettel_account
 * @property string $msisdn
 * @property int $status
 * @property string $merchant_code
 * @property string $order_code
 * @property int $amount
 * @property int $base_price
 * @property string $pay_code
 * @property string $vt_transaction_id
 * @property string $sub_id
 * @property clob $url_redirect
 * @property string $request_id
 * @property int $refund_status
 * @property clob $refund_reason
 * @property datetime $refund_time
 * @property int $refund_amount
 * @property string $ip
 * @property string $status_call_api
 * @property string $payment_source
 * @property string $viettelid_point
 * @property int $status_viettel_id
 * @property int $refund_viettel_id
 * 
 * @method string             getTransactionId()     Returns the current record's "transaction_id" value
 * @method string             getDescription()       Returns the current record's "description" value
 * @method string             getMyviettelAccount()  Returns the current record's "myviettel_account" value
 * @method string             getMsisdn()            Returns the current record's "msisdn" value
 * @method int                getStatus()            Returns the current record's "status" value
 * @method string             getMerchantCode()      Returns the current record's "merchant_code" value
 * @method string             getOrderCode()         Returns the current record's "order_code" value
 * @method int                getAmount()            Returns the current record's "amount" value
 * @method int                getBasePrice()         Returns the current record's "base_price" value
 * @method string             getPayCode()           Returns the current record's "pay_code" value
 * @method string             getVtTransactionId()   Returns the current record's "vt_transaction_id" value
 * @method string             getSubId()             Returns the current record's "sub_id" value
 * @method clob               getUrlRedirect()       Returns the current record's "url_redirect" value
 * @method string             getRequestId()         Returns the current record's "request_id" value
 * @method int                getRefundStatus()      Returns the current record's "refund_status" value
 * @method clob               getRefundReason()      Returns the current record's "refund_reason" value
 * @method datetime           getRefundTime()        Returns the current record's "refund_time" value
 * @method int                getRefundAmount()      Returns the current record's "refund_amount" value
 * @method string             getIp()                Returns the current record's "ip" value
 * @method string             getStatusCallApi()     Returns the current record's "status_call_api" value
 * @method string             getPaymentSource()     Returns the current record's "payment_source" value
 * @method string             getViettelidPoint()    Returns the current record's "viettelid_point" value
 * @method int                getStatusViettelId()   Returns the current record's "status_viettel_id" value
 * @method int                getRefundViettelId()   Returns the current record's "refund_viettel_id" value
 * @method PartnerTransaction setTransactionId()     Sets the current record's "transaction_id" value
 * @method PartnerTransaction setDescription()       Sets the current record's "description" value
 * @method PartnerTransaction setMyviettelAccount()  Sets the current record's "myviettel_account" value
 * @method PartnerTransaction setMsisdn()            Sets the current record's "msisdn" value
 * @method PartnerTransaction setStatus()            Sets the current record's "status" value
 * @method PartnerTransaction setMerchantCode()      Sets the current record's "merchant_code" value
 * @method PartnerTransaction setOrderCode()         Sets the current record's "order_code" value
 * @method PartnerTransaction setAmount()            Sets the current record's "amount" value
 * @method PartnerTransaction setBasePrice()         Sets the current record's "base_price" value
 * @method PartnerTransaction setPayCode()           Sets the current record's "pay_code" value
 * @method PartnerTransaction setVtTransactionId()   Sets the current record's "vt_transaction_id" value
 * @method PartnerTransaction setSubId()             Sets the current record's "sub_id" value
 * @method PartnerTransaction setUrlRedirect()       Sets the current record's "url_redirect" value
 * @method PartnerTransaction setRequestId()         Sets the current record's "request_id" value
 * @method PartnerTransaction setRefundStatus()      Sets the current record's "refund_status" value
 * @method PartnerTransaction setRefundReason()      Sets the current record's "refund_reason" value
 * @method PartnerTransaction setRefundTime()        Sets the current record's "refund_time" value
 * @method PartnerTransaction setRefundAmount()      Sets the current record's "refund_amount" value
 * @method PartnerTransaction setIp()                Sets the current record's "ip" value
 * @method PartnerTransaction setStatusCallApi()     Sets the current record's "status_call_api" value
 * @method PartnerTransaction setPaymentSource()     Sets the current record's "payment_source" value
 * @method PartnerTransaction setViettelidPoint()    Sets the current record's "viettelid_point" value
 * @method PartnerTransaction setStatusViettelId()   Sets the current record's "status_viettel_id" value
 * @method PartnerTransaction setRefundViettelId()   Sets the current record's "refund_viettel_id" value
 * 
 * @package    cms_ctt
 * @subpackage model
 * @author     viettel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePartnerTransaction extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('partner_transaction');
        $this->hasColumn('transaction_id', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Mã giao dịch do viettel tự sinh',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Mô tả giao dịch',
             'length' => 255,
             ));
        $this->hasColumn('myviettel_account', 'string', 50, array(
             'type' => 'string',
             'comment' => 'Số điện thoại lấy dựa theo trường sub_id',
             'length' => 50,
             ));
        $this->hasColumn('msisdn', 'string', 50, array(
             'type' => 'string',
             'comment' => 'số điện thoại thực hiện thanh toán bằng điểm viettel++',
             'length' => 50,
             ));
        $this->hasColumn('status', 'int', 2, array(
             'type' => 'int',
             'comment' => 'Trạng thái giao dịch 1: trừ điểm hoặc trừ tiền thành công',
             'length' => 2,
             ));
        $this->hasColumn('merchant_code', 'string', 50, array(
             'type' => 'string',
             'comment' => 'Mã đối tác',
             'length' => 50,
             ));
        $this->hasColumn('order_code', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Mã đơn hàng của đối tác',
             'length' => 255,
             ));
        $this->hasColumn('amount', 'int', 11, array(
             'type' => 'int',
             'comment' => 'Tổng tiền phải thanh toán',
             'length' => 11,
             ));
        $this->hasColumn('base_price', 'int', 11, array(
             'type' => 'int',
             'comment' => 'Số tiền đơn hàng của đối tác',
             'length' => 11,
             ));
        $this->hasColumn('pay_code', 'string', 50, array(
             'type' => 'string',
             'comment' => 'Mã hình thức thanh toán',
             'length' => 50,
             ));
        $this->hasColumn('vt_transaction_id', 'string', 255, array(
             'type' => 'string',
             'comment' => 'transaction_id khi đối tác vào từ webview tích hợp trên myviettel',
             'length' => 255,
             ));
        $this->hasColumn('sub_id', 'string', 255, array(
             'type' => 'string',
             'comment' => 'sub_id khi đối tác vào từ webview tích hợp trên myviettel',
             'length' => 255,
             ));
        $this->hasColumn('url_redirect', 'clob', null, array(
             'type' => 'clob',
             'comment' => 'Lưu thông tin url redirect',
             ));
        $this->hasColumn('request_id', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Mã giao dịch của cổng thanh toán trả về',
             'length' => 255,
             ));
        $this->hasColumn('refund_status', 'int', 2, array(
             'type' => 'int',
             'comment' => 'Trạng thái hoàn tiền( 1: chờ xác nhận hoàn tiền, 2: hoàn tiền thành công, 3: hoàn tiền thất bại)',
             'length' => 2,
             ));
        $this->hasColumn('refund_reason', 'clob', null, array(
             'type' => 'clob',
             'comment' => 'Lý do hoàn tiền',
             ));
        $this->hasColumn('refund_time', 'datetime', null, array(
             'type' => 'datetime',
             'comment' => 'Thời gian hoàn tiền',
             ));
        $this->hasColumn('refund_amount', 'int', 11, array(
             'type' => 'int',
             'comment' => 'Số tiền hoàn',
             'length' => 11,
             ));
        $this->hasColumn('ip', 'string', 50, array(
             'type' => 'string',
             'comment' => 'Địa chỉ ip gọi vào',
             'length' => 50,
             ));
        $this->hasColumn('status_call_api', 'string', 2, array(
             'type' => 'string',
             'comment' => '00: thành công, còn lại là thất bại',
             'length' => 2,
             ));
        $this->hasColumn('payment_source', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Nguồn tiền thanh toán',
             'length' => 255,
             ));
        $this->hasColumn('viettelid_point', 'string', 255, array(
             'type' => 'string',
             'comment' => '',
             'length' => 255,
             ));
        $this->hasColumn('status_viettel_id', 'int', 2, array(
             'type' => 'int',
             'comment' => 'Trạng thái trừ điểm',
             'length' => 2,
             ));
        $this->hasColumn('refund_viettel_id', 'int', 2, array(
             'type' => 'int',
             'comment' => 'Trạng thái giao dịch 1: Trạng thái hoàn điểm',
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}