<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('VtOmniOrderHis', 'doctrine');

/**
 * BaseVtOmniOrderHis
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $order_code
 * @property integer $msisdn
 * @property integer $error_code
 * @property clob $response
 * @property clob $order_content
 * @property string $source
 * @property string $order_type
 * 
 * @method string         getOrderCode()     Returns the current record's "order_code" value
 * @method integer        getMsisdn()        Returns the current record's "msisdn" value
 * @method integer        getErrorCode()     Returns the current record's "error_code" value
 * @method clob           getResponse()      Returns the current record's "response" value
 * @method clob           getOrderContent()  Returns the current record's "order_content" value
 * @method string         getSource()        Returns the current record's "source" value
 * @method string         getOrderType()     Returns the current record's "order_type" value
 * @method VtOmniOrderHis setOrderCode()     Sets the current record's "order_code" value
 * @method VtOmniOrderHis setMsisdn()        Sets the current record's "msisdn" value
 * @method VtOmniOrderHis setErrorCode()     Sets the current record's "error_code" value
 * @method VtOmniOrderHis setResponse()      Sets the current record's "response" value
 * @method VtOmniOrderHis setOrderContent()  Sets the current record's "order_content" value
 * @method VtOmniOrderHis setSource()        Sets the current record's "source" value
 * @method VtOmniOrderHis setOrderType()     Sets the current record's "order_type" value
 * 
 * @package    cms_ctt
 * @subpackage model
 * @author     viettel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVtOmniOrderHis extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vt_omni_order_his');
        $this->hasColumn('order_code', 'string', 50, array(
             'type' => 'string',
             'comment' => 'Ma don hang',
             'length' => 50,
             ));
        $this->hasColumn('msisdn', 'integer', 20, array(
             'type' => 'integer',
             'comment' => 'So dien thoai',
             'length' => 20,
             ));
        $this->hasColumn('error_code', 'integer', 11, array(
             'type' => 'integer',
             'comment' => '(0: thanh cong, 1: that bai)',
             'length' => 11,
             ));
        $this->hasColumn('response', 'clob', null, array(
             'type' => 'clob',
             'comment' => 'response tra ve tu ws khi dat hang',
             ));
        $this->hasColumn('order_content', 'clob', null, array(
             'type' => 'clob',
             'comment' => 'thong tin don hang',
             ));
        $this->hasColumn('source', 'string', 20, array(
             'type' => 'string',
             'comment' => 'APP,WEB,WAP',
             'length' => 20,
             ));
        $this->hasColumn('order_type', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Loại đơn hàng: 1- Đấu nối sim trả trước, 2- trả sau,..',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}