<?php

/**
 * FlashSaleLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cms_ctt
 * @subpackage model
 * @author     viettel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class FlashSaleLog extends BaseFlashSaleLog
{
    public function getProcessedName(){
        return self::getArr($this->getProcessed());
    }
    public function getRegisterStatusName(){
        return self::getName($this->getRegisterStatus());
    }
    public static function getArr($type){
        $i18n = sfContext::getInstance()->getI18N();
        if($type === 0 || $type === '0'){
            $message =  $i18n->__('Chưa tặng thẻ cào');
        }elseif($type == 1){
            $message =  $i18n->__('Đã tặng thẻ cào');
        }else{
            $message = '';
        }
        return $message;
    }
    public static function getName($type){
        $i18n = sfContext::getInstance()->getI18N();
        if($type === 0 || $type === '0'){
            $message =  $i18n->__('Thành công');
        }elseif($type == 1){
            $message =  $i18n->__('Thất bại');
        }else{
            $message = '';
        }
        return $message;
    }
}