<?php

/**
 * FlashSaleLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FlashSaleLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FlashSaleLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FlashSaleLog');
    }
}