<?php

/**
 * MerchantOrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MerchantOrderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MerchantOrderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MerchantOrder');
    }
}