<?php

/**
 * PartnerTransaction
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cms_ctt
 * @subpackage model
 * @author     viettel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PartnerTransaction extends BasePartnerTransaction
{
    public function getStatusName(){
        return self::getName($this->getStatus(),$this->getPayCode());
    }

    public function getStatusViettelIdName(){
        return self::getViettelIdName($this->getStatusViettelId(),$this->getPayCode());
    }

    public function getRefundViettelIdName(){
        return self::getRefundName($this->getRefundViettelId());
    }

    public function getRefundStatusName(){
        return self::getArr($this->getRefundStatus());
    }

    public static function getName($name, $payCode){
        $i18n = sfContext::getInstance()->getI18N();

        if($name == 1)
        {
            $statusName = $i18n->__('Thanh toán thành công');
        }
        elseif($name === '0' || $name === 0){
            $statusName = $i18n->__('Thanh toán thất bại');
        }else{
            $statusName = '';
        }
        $pos = strpos($payCode, ',');
        if ($pos === false && $payCode == 'VIETTELID') {
            $statusName = '';
        }
//        $name == 1 ? $statusName = $i18n->__('Thanh toán thành công') : $statusName = $i18n->__('Thanh toán thất bại');
        return $statusName;
    }

    public static function getViettelIdName($name, $payCode){
        $i18n = sfContext::getInstance()->getI18N();
        if($name == 1)
        {
            $statusName = $i18n->__('Trừ điểm thành công');
        }
        elseif($name === '0' || $name === 0){
            $statusName = $i18n->__('Trừ điểm thất bại');
        }else{
            $statusName = '';
        }
        $pos = strpos($payCode, ',');
        if ($pos === false && $payCode != 'VIETTELID') {
            $statusName = '';
        }
//        $name == 1 ? $statusName = $i18n->__('Trừ điểm thành công') : $statusName = $i18n->__('Trừ điểm thất bại');
        return $statusName;
    }
    public static function getRefundName($name){
        $i18n = sfContext::getInstance()->getI18N();
        $name == 1 ? $statusName = $i18n->__('Hoàn điểm thành công') : $name === NULL ? '' : $statusName = $i18n->__('Hoàn điểm thất bại');
        return $statusName;
    }

    public static function getArr($type){
        $i18n = sfContext::getInstance()->getI18N();
        switch ($type){
            case 1:
                $message =  $i18n->__('Đã gửi yêu cầu hoàn tiền, đang chờ xác nhận hoàn tiền');
                break;
            case 2:
                $message =  $i18n->__('Hoàn tiền thành công');
                break;
            case 3:
                $message = $i18n->__('Hoàn tiền thất bại');
                break;
            case 4:
                $message =  $i18n->__('Đã từ chối');
                break;
            case 5:
                $message =  $i18n->__('Đã duyệt yêu cầu hoàn tiền');
                break;
            case 6:
                $message =  $i18n->__('Gửi yêu cầu hoàn tiền thất bại');
                break;
            default:
                $message =  $i18n->__('');
                break;
        }
        return $message;
    }
    public static function genRandomNumber($length = 8)
    {
        $characters = '0123456789';
        $string = '';

        for ($p = 0; $p < $length; $p++) {
            $string .= $characters[mt_rand(0, strlen($characters) - 1)];
        }

        return $string;
    }

    public function isVnPayMethod(){
      $payCode = str_replace("VIETTELID,", "", $this->getPayCode());
      $payCode = str_replace(",", "", $payCode);
      return in_array($payCode, VnPayPayCodeEnum::getListPayCodeVnPay());
    }
}