<?php

/**
 * PartnerTransactionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PartnerTransactionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PartnerTransactionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PartnerTransaction');
    }
}