<?php

/**
 * VtAreaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VtAreaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VtAreaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VtArea');
    }

}