<?php

/**
 * VtCttRefundLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VtCttRefundLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VtCttRefundLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VtCttRefundLog');
    }
}