<?php

/**
 * VtCttRefundLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cms_ctt
 * @subpackage model
 * @author     viettel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class VtCttRefundLog extends BaseVtCttRefundLog
{

}