<?php

/**
 * VtOmniOrderHisTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VtOmniOrderHisTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VtOmniOrderHisTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VtOmniOrderHis');
    }
}