<?php

/**
 * VtOmniOrderHis
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    cms_ctt
 * @subpackage model
 * @author     viettel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class VtOmniOrderHis extends BaseVtOmniOrderHis
{
    public function getOrderType()
    {
        $i18n = sfContext::getInstance()->getI18N();
        $content = json_decode($this->getOrderContent());
        return $content->custAcceptAIResult == false ? $i18n->__('Thủ công') : $i18n->__('Tự động');
    }

    public function getStatus()
    {
        $i18n = sfContext::getInstance()->getI18N();
        $status = json_decode($this->getErrorCode());
        if ($this->getOrderType() == $i18n->__('Thủ công') && $status == 0) {
            return $i18n->__('Chờ kiểm duyệt');
        }
        return $status == 0 ? $i18n->__('Thành công') : $i18n->__('Thất bại');
    }

    public function getSourceName()
    {
        $i18n = sfContext::getInstance()->getI18N();
        return $i18n->__('App');
    }
}