<?php

/**
 * VtPaymentDebtTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VtPaymentDebtTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VtPaymentDebtTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VtPaymentDebt');
    }
}