<?php

/**
 * VtVpgTransaction
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cms_ctt
 * @subpackage model
 * @author     viettel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class VtVpgTransaction extends BaseVtVpgTransaction
{
  public function getStatusName(){
    return VtVpgStatusEnum::getStatusName($this->getStatus());
  }
  public function getAmountFormat(){
    return VtHelper::formatNumber($this->getAmount());
  }
  public function getRefundStatus(){
    $status = "";
    if($this->getStatus() == VtVpgStatusEnum::ORDER_FAIL)
      $status = $this->getIsRefund() ? 'Đã hoàn tiền' : 'Chưa hoàn tiền';
    return $status;
  }
}