<?php

/**
 * VtVpgTransactionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VtVpgTransactionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VtVpgTransactionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VtVpgTransaction');
    }
}