generator:
  class: tmcTwitterBootstrapDoctrineGenerator
  param:
    model_class:           VtCttTransaction
    theme:                 tmcTwitterBootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          vt_ctt_transaction
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Omni Sim Report
        display: [order_no,isdn,sim_number,omni_order_code,contact_phone,sim_price_format,main_package_price_format,other_service_price_format,transport_fee_format,amount_format,updated_at,omni_error_code_name,tran_id,receive_type_name,channel_name]
        fields:
          tran_id: {label: Transaction Id}
          omni_error_code_name: {label: Status}
          updated_at: {label: Order time}
          sim_price_format: {label: Sim price}
          main_package_price_format: {label: Main package price}
          other_service_price_format: {label: Other service price}
          transport_fee_format: {label: Transport fee}
          amount_format: {label: Amount}
          isdn: {label: Isdn login}
          receive_type_name: {label: Receive type}
          source: {label: Channel}
          omni_order_code: {label: Mã đơn hàng omni}
        object_actions: {}
        batch_actions: {}
        actions: {}
      filter:
        class: VtOmniReportAdminFormFilter
      form:    ~
      edit:    ~
      new:     ~
      show:    ~
      revert:  ~