generator:
  class: tmcTwitterBootstrapDoctrineGenerator
  param:
    model_class:           VtCttTransaction
    theme:                 tmcTwitterBootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          vt_ctt_transaction_vtCttReport
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Thống kê giao dịch qua CTT, Ví Viettelpay
        display: [order_no,isdn_login,isdn,tran_id,order_type_name,package_name, base_price,amount_format,source,omni_error_code_name,updated_at,ctt_id,bank_code,status_name,refund_status_name]
        fields:
          isdn: {label: Thuê bao được cung cấp dịch vụ}
          updated_at: {label: Thời gian phát sinh giao dịch}
          amount_format: {label: Charge amount}
          base_price: {label: Giá gốc}
          source: {label: Channel}
          status_name: {label: Trạng thái trừ tiền}
          omni_error_code_name: {label: Trạng thái cung cấp dịch vụ}
          tran_id: {label: Transaction Id}
          ctt_id: {label: Ctt Id}
          order_type_name: {label: Loại giao dịch}
          package_name: {label: Gói cước đăng ký}
          bank_code: {label: Nguồn tiền}
          refund_status_name: {label: Trạng thái hoàn tiền}
        object_actions: {}
        actions: {}
        batch_actions: {}
      filter:
        class: VtCttReportAdminFormFilter
      form:    ~
      edit:    ~
      new:     ~
      show:    ~
      revert:  ~