generator:
  class: tmcTwitterBootstrapDoctrineGenerator
  param:
    model_class:           VtCttTransaction
    theme:                 tmcTwitterBootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          vt_ctt_transaction_vtPackageRevenueReport
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Data,vas revenue report
        display: [order_no,isdn,ctt_package,service_pay,updated_at,source,ctt_id,tran_id,amount,omni_error_code_name, channel_name]
        fields:
          tran_id: {label: Transaction Id}
          omni_error_code_name: {label: Status}
          isdn: {label: Isdn register package}
          source: {label: Channel}
          updated_at: {label: Registered time}
          ctt_id: {label: Ctt Id}
        object_actions: {}
        batch_actions: {}
        actions: {}
      filter:
        class: VtPackageRevenueReportAdminFormFilter
      form:    ~
      edit:    ~
      new:     ~
      show:    ~
      revert:  ~