generator:
  class: tmcTwitterBootstrapDoctrineGenerator
  param:
    model_class:           VtCttTransaction
    theme:                 tmcTwitterBootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          vt_ctt_transaction_vtOmniRevenueReport
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Omni Sim Revenue Report
        display: [order_no,omni_order_code,isdn,sim_number,main_package,vas_package,source,updated_at,ctt_id,tran_id,sim_price_format,main_package_price_format,vas_price_format,transport_fee_format,amount_format,omni_error_code_name, channel_name]
        fields:
          tran_id: {label: Transaction Id}
          omni_error_code_name: {label: Status}
          updated_at: {label: Order time}
          sim_price_format: {label: Sim price}
          main_package_price_format: {label: Main package price}
          other_service_price_format: {label: Other service price}
          transport_fee_format: {label: Transport fee}
          amount_format: {label: Amount}
          isdn: {label: Isdn login}
          receive_type_name: {label: Receive type}
          ctt_id: {label: Ctt Id}
          vas_price_format: {label: Vas price}
          source: {label: Sell channel},
          omni_order_code: {label: Mã đơn hàng omni}
        object_actions: {}
        batch_actions: {}
        actions: {}
      filter:
        class: VtOmniRevenueReportAdminFormFilter
      form:    ~
      edit:    ~
      new:     ~
      show:    ~
      revert:  ~